
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const PUT_AVATAR = "PUT_AVATAR"
export const LOG_OUT = "LOG_OUT"



