
export const GET_CONVERSATION_PENDING = "GET_CONVERSATION_PENDING"
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS"
export const GET_CONVERSATION_FAIL = "GET_CONVERSATION_FAIL"
export const SELECTED_CONVERSATION = "SELECTED_CONVERSATION"
export const ADD_CONVERSATION = "ADD_CONVERSATION"
export const RESET_CONVERSATION = "RESET_CONVERSATION"
export const ADD_LATEST_MSG = "ADD_LATEST_MSG"
export const CHANGE_TOPIC = "CHANGE_TOPIC"
export const DELETE_CONVERSATION = "DELETE_CONVERSATION"
export const LEAVE_GROUP_CONVERSATION = "LEAVE_GROUP_CONVERSATION"
export const ADD_MEMBER_CONVERSATION = "ADD_MEMBER_CONVERSATION"
export const DELETE_MEMBER_CONVERSATION = "DELETE_MEMBER_CONVERSATION"
export const CHANGE_INFOR_CONVERSATION = "CHANGE_INFOR_CONVERSATION"











