export const GET_NOTIFICATION_PENDING = "GET_NOTIFICATION_PENDING"
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS"
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL"
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION"
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"



