
export const GET_POST_PENDING = "GET_POST_PENDING"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAIL = "GET_POST_FAIL"
export const CREATE_POST = "CREATE_POST"
export const HANDLE_REACTION_POST = "HANDLE_REACTION_POST"
export const RESET_POST = "RESET_POST"
export const ADD_POST = "ADD_POST"
export const INCREASE_COMMENT_POST = "INCREASE_COMMENT_POST"





